config/routes.rb
Rails.application.routes.draw do
  root "billets#index"
  resources :billets
  mount GoodJob::Engine, at: "good_job"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/billet.rb
class Billet < ApplicationRecord

  validates :customer_cnpj_cpf, presence: true, length: { in: 11..14 }

  validates :expire_at,
            :customer_person_name,
            :customer_cnpj_cpf,
            :customer_city_name,
            :customer_state,
            :customer_city_name,
            :customer_zipcode,
            :customer_address,
            :customer_neighborhood,
            presence: true

  validate :verify_expire_at
  validate :validar_cpf_ou_cnpj

  after_create :generate_billet
  after_update :update_billet

  scope :by_customer_person_name, ->(name) { where('customer_person_name ILIKE ?', "%#{name}%") if name.present? }
  scope :by_customer_cnpj_cpf, ->(cnpj_cpf) { where('customer_cnpj_cpf LIKE ?', "#{cnpj_cpf}%") if cnpj_cpf.present? }
  scope :by_customer_situation, ->(situation) { where(customer_situation: situation) if situation.present? }

  scope :by_expire_at, ->(start_expire_at, end_expire_at) do
    if(start_expire_at.present? && end_expire_at.present?)
      where(expire_at: (start_expire_at..end_expire_at))
    elsif start_expire_at.present?
      where('billets.expire_at >= ?', start_expire_at)
    elsif end_expire_at.present?
      where('billets.expire_at <= ?', end_expire_at)
    end
  end

  scope :ordered, -> { order(expire_at: :desc) }


  def self.search(search_params)
    by_customer_person_name(search_params[:customer_person_name])
      .merge(by_customer_cnpj_cpf(search_params[:customer_cnpj_cpf]))
      .merge(by_expire_at(search_params[:start_expire_at], search_params[:end_expire_at]))
      .merge(by_customer_situation(search_params[:customer_situation]))
      .ordered
  end

  private

  def generate_billet
    KobanaJob.perform_now('post', self)
  end

  def update_billet
    KobanaJob.perform_now('put', self)
  end

  def validar_cpf_ou_cnpj
    unless check_cpf(customer_cnpj_cpf) || check_cnpj(customer_cnpj_cpf)
      errors.add(:customer_cnpj_cpf, :invalid_cnpj_cpf)
    end
  end

  def verify_expire_at
    if  expire_at.present?
      errors.add(:expire_at, :previous_date) if Date.today > expire_at
      errors.add(:expire_at, :weekend) if [0, 6].include?(expire_at.wday)
    end
  end

  def check_cpf(cpf=nil)
    return false if cpf.nil?

    nulos = %w{12345678909 11111111111 22222222222 33333333333 44444444444 55555555555 66666666666 77777777777 88888888888 99999999999 00000000000 12345678909}
    valor = cpf.scan /[0-9]/
    if valor.length == 11
      unless nulos.member?(valor.join)
        valor = valor.collect{|x| x.to_i}
        soma = 10*valor[0]+9*valor[1]+8*valor[2]+7*valor[3]+6*valor[4]+5*valor[5]+4*valor[6]+3*valor[7]+2*valor[8]
        soma = soma - (11 * (soma/11))
        resultado1 = (soma == 0 or soma == 1) ? 0 : 11 - soma
        if resultado1 == valor[9]
          soma = valor[0]*11+valor[1]*10+valor[2]*9+valor[3]*8+valor[4]*7+valor[5]*6+valor[6]*5+valor[7]*4+valor[8]*3+valor[9]*2
          soma = soma - (11 * (soma/11))
          resultado2 = (soma == 0 or soma == 1) ? 0 : 11 - soma
          return true if resultado2 == valor[10] # CPF válido
        end
      end
    end
    return false
  end

  def check_cnpj(cnpj=nil)
    return false if cnpj.nil?

    nulos = %w{11111111111111 22222222222222 33333333333333 44444444444444 55555555555555 66666666666666 77777777777777 88888888888888 99999999999999 00000000000000}
    valor = cnpj.scan /[0-9]/
    if valor.length == 14
      unless nulos.member?(valor.join)
        valor = valor.collect{|x| x.to_i}
        soma = valor[0]*5+valor[1]*4+valor[2]*3+valor[3]*2+valor[4]*9+valor[5]*8+valor[6]*7+valor[7]*6+valor[8]*5+valor[9]*4+valor[10]*3+valor[11]*2
        soma = soma - (11*(soma/11))
        resultado1 = (soma==0 || soma==1) ? 0 : 11 - soma
        if resultado1 == valor[12]
          soma = valor[0]*6+valor[1]*5+valor[2]*4+valor[3]*3+valor[4]*2+valor[5]*9+valor[6]*8+valor[7]*7+valor[8]*6+valor[9]*5+valor[10]*4+valor[11]*3+valor[12]*2
          soma = soma - (11*(soma/11))
          resultado2 = (soma == 0 || soma == 1) ? 0 : 11 - soma
          return true if resultado2 == valor[13] # CNPJ válido
        end
      end
    end
    return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/billets_controller.rb
class BilletsController < ApplicationController
  before_action :set_billet, only: %i[ show edit update destroy ]

  def index
    @billets = Billet.search(search_params)
  end

  def show
  end

  def new
    @billet = Billet.new
  end

  def edit
  end

  def create
    @billet = Billet.new(billet_params)

    respond_to do |format|
      if @billet.save
        format.html { redirect_to billet_url(@billet), notice: t('.created') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @billet.update(billet_params)
        format.html { redirect_to billet_url(@billet), notice: t('.edited') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @billet.destroy!

    respond_to do |format|
      format.html { redirect_to billets_url, notice: t('.destroyed') }
    end
  end

  private
    def set_billet
      @billet = Billet.find(params[:id])
    end

    def search_params
      params
        .permit(:customer_person_name, :customer_cnpj_cpf, :customer_situation, :start_expire_at, :end_expire_at)
    end

    def billet_params
      params.require(:billet).permit(:amount, :expire_at, :customer_person_name, :customer_cnpj_cpf, :customer_state, :customer_city_name, :customer_zipcode, :customer_address, :customer_neighborhood, :customer_number, :customer_complement)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/billets/_billet.html.erb
<div class='w-full p-6 bg-white rounded hover:shadow-md hover:bg-gray-50 text-base text-gray-600'>
  <div class="flex justify-between py-1 text-lg ">
    <div class="">
      <%= billet.customer_person_name %>
    </div>

    <div class="font-bold">
      <%== t(".situation.#{billet.customer_situation}") if billet.customer_situation.present?  %>
    </div>
  </div>
  
  <div class="h-36 p-5 border-4 border-dashed border-gray-100">
    <div class="flex justify-between">
      <span class="text-base text-gray-600" >Id: #<%= billet.external_id %> </span>
      <span class="text-base text-gray-600" >CPF/CNPJ:  <%= billet.customer_cnpj_cpf %> </span>
    </div>
    <div class="flex flex-row justify-between text-black">
      <div class="flex flex-col justify-between font-semibold text-2xl">
        R$ <%= number_with_precision(billet.amount, precision: 2) %>
        <span class="text-base text-gray-600" >Valor</span>
      </div>
      
      <div class="flex flex-col justify-between font-semibold text-2xl">
        <%= l(billet.expire_at, format: :default ) %> 
        <span class="text-base text-gray-600" >Vencimento</span>
      </div>
    </div>
  </div>

  <div class="w-full flex justify-between mt-2 py-1">
    <div class="flex space-x-5">
      <%= link_to edit_billet_path(billet) do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="fill-black hover:fill-gray-500" width="30" height="30" viewBox="0 0 24 24"><path d="M19.045 7.401c.378-.378.586-.88.586-1.414s-.208-1.036-.586-1.414l-1.586-1.586c-.378-.378-.88-.586-1.414-.586s-1.036.208-1.413.585L4 13.585V18h4.413L19.045 7.401zm-3-3 1.587 1.585-1.59 1.584-1.586-1.585 1.589-1.584zM6 16v-1.585l7.04-7.018 1.586 1.586L7.587 16H6zm-2 4h16v2H4z"></path></svg>
      <% end %>

      <svg xmlns="http://www.w3.org/2000/svg" class="fill-black hover:fill-gray-500 hover:opacity-0 " width="30" height="30" viewBox="0 0 24 24"><path d="M11 10H9v3H6v2h3v3h2v-3h3v-2h-3z"></path><path d="M4 22h12c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2H4c-1.103 0-2 .897-2 2v12c0 1.103.897 2 2 2zM4 8h12l.002 12H4V8z"></path><path d="M20 2H8v2h12v12h2V4c0-1.103-.897-2-2-2z"></path></svg>
      
      <%= link_to billet do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="fill-black hover:fill-gray-500"width="35" height="35" viewBox="0 0 24 24"><path d="M12.015 7c4.751 0 8.063 3.012 9.504 4.636-1.401 1.837-4.713 5.364-9.504 5.364-4.42 0-7.93-3.536-9.478-5.407 1.493-1.647 4.817-4.593 9.478-4.593zm0-2c-7.569 0-12.015 6.551-12.015 6.551s4.835 7.449 12.015 7.449c7.733 0 11.985-7.449 11.985-7.449s-4.291-6.551-11.985-6.551zm-.015 5c1.103 0 2 .897 2 2s-.897 2-2 2-2-.897-2-2 .897-2 2-2zm0-2c-2.209 0-4 1.792-4 4 0 2.209 1.791 4 4 4s4-1.791 4-4c0-2.208-1.791-4-4-4z"/></svg>
      <% end %>
      
      <svg xmlns="http://www.w3.org/2000/svg" class="fill-black hover:fill-red-400 " width="30" height="30" viewBox="0 0 24 24"><path d="M8.267 14.68c-.184 0-.308.018-.372.036v1.178c.076.018.171.023.302.023.479 0 .774-.242.774-.651 0-.366-.254-.586-.704-.586zm3.487.012c-.2 0-.33.018-.407.036v2.61c.077.018.201.018.313.018.817.006 1.349-.444 1.349-1.396.006-.83-.479-1.268-1.255-1.268z"></path><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6zM9.498 16.19c-.309.29-.765.42-1.296.42a2.23 2.23 0 0 1-.308-.018v1.426H7v-3.936A7.558 7.558 0 0 1 8.219 14c.557 0 .953.106 1.22.319.254.202.426.533.426.923-.001.392-.131.723-.367.948zm3.807 1.355c-.42.349-1.059.515-1.84.515-.468 0-.799-.03-1.024-.06v-3.917A7.947 7.947 0 0 1 11.66 14c.757 0 1.249.136 1.633.426.415.308.675.799.675 1.504 0 .763-.279 1.29-.663 1.615zM17 14.77h-1.532v.911H16.9v.734h-1.432v1.604h-.906V14.03H17v.74zM14 9h-1V4l5 5h-4z"></path></svg>
    </div>
    
    <div>
      <%= button_to  billet, form: { data: { turbo_confirm: t('.delete') } }, method: :delete do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="fill-black hover:fill-red-400 " width="30" height="30" viewBox="0 0 24 24"><path d="M5 20a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8h2V6h-4V4a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2v2H3v2h2zM9 4h6v2H9zM8 8h9v12H7V8z"></path><path d="M9 10h2v8H9zm4 0h2v8h-2z"></path></svg>
      <% end %>
    </div>
  </div>
  
</div>

app/views/billets/_form.html.erb
<div class="mt-4 ">
  <div class="p-6 bg-white rounded-md shadow-md">
    <h2 class="text-lg font-semibold text-gray-700 capitalize">
      Dados do boleto
    </h2>
    <%= form_with(model: billet, class: "contents", data:{ controller: 'billets' }) do |form| %>
      <% if billet.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
          <h2><%= t('.error')%></h2>
          <ul>
            <% billet.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="w-full grid grid-cols-2 gap-x-2 gap-y-2 ">
        
        <div class="col-span-2">
          <%= form.label :customer_person_name, class:"text-base" %>
          <%= form.text_field :customer_person_name, placeholder: t('.customer_person_name'),required: true,
            class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
        </div>
        
        <div class="col-span-2">
          <%= form.label :customer_cnpj_cpf, class:"text-base" %>
          <%= form.text_field :customer_cnpj_cpf, placeholder: t('.customer_cnpj_cpf'), required: true,
            maxlength: 14, minlength: 11,
            class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
        </div>
        
        <div class="grid grid-cols-subgrid col-span-2 md:col-span-2">
          <div class="col-span-1">
            <%= form.label :amount, class:"text-base" %>
            <%= form.text_field :amount, placeholder: t('.amount'), required: true,
              class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
          </div>
          <div class="col-span-1">
            <%= form.label :expire_at, class:"text-base" %>
            <%= form.date_field :expire_at, placeholder: t('.expire_at'), required: true,
              class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
          </div>
        </div>

        <div class="col-span-1">
          <%= form.label :customer_zipcode, class:"text-base" %>
          <%= form.text_field :customer_zipcode, placeholder: t('.customer_zipcode'), required: true,
              data:{ action:'input->billets#findAddress' },
            class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
        </div>

        <div class="grid grid-cols-subgrid col-start-1 col-span-2 md:col-span-2">
          <div class="col-span-1">
            <%= form.label :customer_address, class:"text-base" %>
            <%= form.text_field :customer_address, placeholder: t('.customer_address'),required: true,
              data: {  'billets-target': 'address' },
              class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
          </div>
          <div class="col-span-1">
            <%= form.label :customer_number, class:"text-base" %>
            <%= form.text_field :customer_number, placeholder: t('.customer_number'),
              class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
          </div>
        </div>

        <div class="col-span-1">
          <%= form.label :customer_complement, class:"text-base" %>
          <%= form.text_field :customer_complement, placeholder: t('.customer_complement'),
            class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
        </div>
        <div class="col-span-1">
          <%= form.label :customer_state, class:"text-base" %>  
          <%= form.text_field :customer_state, required: true,
            data: {  'billets-target': 'state' },
            class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
        </div>
        <div class="col-span-1">
          <%= form.label :customer_city_name, class:"text-base" %>
          <%= form.text_field :customer_city_name, required: true,
            data: {  'billets-target': 'city_name' },
            class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
        </div>
        <div class="col-span-1">
          <%= form.label :customer_neighborhood, class:"text-base" %>
          <%= form.text_field :customer_neighborhood, required: true,
            data: {  'billets-target': 'neighborhood' },
            class: "w-full mt-1 border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500" %>
        </div>

        <div class="flex justify-start space-x-2 mt-4">
          <%= form.submit class: "px-4 py-2 text-gray-200 bg-gray-800 rounded-md hover:bg-gray-700 focus:outline-none focus:bg-gray-900" %>
          <%= link_to "Cancelar", billets_path, class: "px-4 py-2 text-gray-200 bg-gray-800 rounded-md hover:bg-gray-700 focus:outline-none focus:bg-gray-900" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/billets/_search_area.html.erb
<%= form_with url: billets_path, method: :get, class:'grid grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6 gap-2' do |form| %>
  <div class="col-span-1">
    <%= form.label :customer_person_name, t(".customer_person_name")[0], class:"text-base" %>
    <%= form.text_field :customer_person_name, placeholder: t(".customer_person_name")[1], value: params[:customer_person_name], class: 'w-full border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500' %>
  </div>
  <div class="col-span-1">
    <%= form.label :customer_cnpj_cpf, t(".customer_cnpj_cpf")[0], class:"text-base" %>
    <%= form.text_field :customer_cnpj_cpf, placeholder: t(".customer_cnpj_cpf")[1], value: params[:customer_cnpj_cpf], class: 'w-full border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500' %>
  </div>

  <div class="col-span-1">
    <%= form.label :start_expire_at, t(".start_expire_at"), class:"text-base" %>
    <%= form.date_field :start_expire_at, value: params[:start_expire_at], class: 'block w-full border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500' %>
  </div>

  <div class="col-span-1">
    <%= form.label :end_expire_at, t(".end_expire_at"), class:"text-base" %>
    <%= form.date_field :end_expire_at, value: params[:end_expire_at], class: 'block w-full border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500' %>
  </div>
 
  <div class="col-span-1 flex items-end">
    <%= form.select :customer_situation, t('.situation').map{|a| a.reverse},
                { prompt: t(".customer_situation") },  
                class: 'block w-full border-gray-500 rounded-md focus:border-indigo-600 focus:ring focus:ring-opacity-40 focus:ring-indigo-500' %>
  </div>

  <div class="col-span-1 flex items-end" >
    <%= button_tag( class: "flex items-center max-w-36 h-10 px-4 py-2 text-gray-200 bg-gray-800 rounded-md hover:bg-gray-700 focus:outline-none focus:bg-gray-900") do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);transform: ;msFilter:;">
        <path d="M10 18a7.952 7.952 0 0 0 4.897-1.688l4.396 4.396 1.414-1.414-4.396-4.396A7.952 7.952 0 0 0 18 10c0-4.411-3.589-8-8-8s-8 3.589-8 8 3.589 8 8 8zm0-14c3.309 0 6 2.691 6 6s-2.691 6-6 6-6-2.691-6-6 2.691-6 6-6z"></path>
        <path d="M11.412 8.586c.379.38.588.882.588 1.414h2a3.977 3.977 0 0 0-1.174-2.828c-1.514-1.512-4.139-1.512-5.652 0l1.412 1.416c.76-.758 2.07-.756 2.826-.002z"></path>
      </svg>
      <span class="mx-1"><%= t('.action')%></span>
    <% end %>
  </div>
  
<% end %>
    

app/views/billets/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="flex justify-between">
    <h1 class="font-bold text-4xl"><%= t(".title") %></h1>
    <%= link_to billets_path do %>
      <%= content_tag :svg, class: 'w-10 h-full', viewBox: '0 0 24 24', fill: 'none' do %>
        <%= content_tag :path, '', d: 'M21 11H6.414l5.293-5.293-1.414-1.414L2.586 12l7.707 7.707 1.414-1.414L6.414 13H21z', fill: 'currentColor' %>
      <% end %>
    <% end %>
  </div>
    <%= render "form", billet: @billet %>
</div>

app/views/billets/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="flex justify-between">
    <h1 class="font-bold text-4xl"><%= t(".title") %></h1>
    <%= link_to billets_path do %>
      <%= content_tag :svg, class: 'w-10 h-full', viewBox: '0 0 24 24', fill: 'none' do %>
        <%= content_tag :path, '', d: 'M21 11H6.414l5.293-5.293-1.414-1.414L2.586 12l7.707 7.707 1.414-1.414L6.414 13H21z', fill: 'currentColor' %>
      <% end %>
    <% end %>
  </div>
  <div class="bg-white rounded-md shadow">
    <div class="flex justify-between p-4 border-b-2 border-gray-400">
      <div class=" text-gray-600 font-semibold">
        <h1 class="text-xl">R$: <%= number_with_precision(@billet.amount, precision: 2) %></h1>
        <span class="text-md"> Vencimento: <%= l(@billet.expire_at) %></span>
      </div>
      <div class="flex items-center">
        <div class="font-bold">
          <%== t(".situation.#{@billet.customer_situation}") if @billet.customer_situation.present?  %>
        </div>  
      </div>
    </div>

    <div class="flex justify-between p-4 ">
      <div class=" text-gray-600 font-semibold">
        <h1 class="text-lg"> Identificador do boleto: #<%= @billet.external_id %></h1>
        <h1 class="text-lg">Nome: <%= @billet.customer_person_name %></h1>
        <h1 class="text-md">CPF / CNPJ: <%= @billet.customer_cnpj_cpf %></h1>
      </div>
    </div>
    
    <div class="flex  p-4 text-gray-600 ">
      <div class="">
        <h1 class="text-lg font-semibold"> Endereço:</h1>
        <h2 class="text-base"> Bairo: <%= @billet.customer_neighborhood %></h1>
        <h2 class="text-base"> Cidade: <%= @billet.customer_city_name %></h1>
        <h2 class="text-base"> Estado: <%= @billet.customer_state %></h1>
        <h2 class="text-base"> Endereço: <%= @billet.customer_address %></h1>
        <h2 class="text-base"> Complemtento: <%= @billet.customer_complement %></h1>
      </div>
    </div>
    <div class="w-full flex justify-between mt-2 py-1 px-4">
      <div class="flex space-x-5">
        <%= link_to edit_billet_path(@billet) do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="fill-black hover:fill-gray-500" width="36" height="36" viewBox="0 0 24 24"><path d="M19.045 7.401c.378-.378.586-.88.586-1.414s-.208-1.036-.586-1.414l-1.586-1.586c-.378-.378-.88-.586-1.414-.586s-1.036.208-1.413.585L4 13.585V18h4.413L19.045 7.401zm-3-3 1.587 1.585-1.59 1.584-1.586-1.585 1.589-1.584zM6 16v-1.585l7.04-7.018 1.586 1.586L7.587 16H6zm-2 4h16v2H4z"></path></svg>
        <% end %>

        <svg xmlns="http://www.w3.org/2000/svg" class="fill-black hover:fill-gray-500 hover:opacity-0 " width="36" height="36" viewBox="0 0 24 24"><path d="M11 10H9v3H6v2h3v3h2v-3h3v-2h-3z"></path><path d="M4 22h12c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2H4c-1.103 0-2 .897-2 2v12c0 1.103.897 2 2 2zM4 8h12l.002 12H4V8z"></path><path d="M20 2H8v2h12v12h2V4c0-1.103-.897-2-2-2z"></path></svg>
        
        <svg xmlns="http://www.w3.org/2000/svg" class="fill-black hover:fill-red-400 " width="36" height="36" viewBox="0 0 24 24"><path d="M8.267 14.68c-.184 0-.308.018-.372.036v1.178c.076.018.171.023.302.023.479 0 .774-.242.774-.651 0-.366-.254-.586-.704-.586zm3.487.012c-.2 0-.33.018-.407.036v2.61c.077.018.201.018.313.018.817.006 1.349-.444 1.349-1.396.006-.83-.479-1.268-1.255-1.268z"></path><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6zM9.498 16.19c-.309.29-.765.42-1.296.42a2.23 2.23 0 0 1-.308-.018v1.426H7v-3.936A7.558 7.558 0 0 1 8.219 14c.557 0 .953.106 1.22.319.254.202.426.533.426.923-.001.392-.131.723-.367.948zm3.807 1.355c-.42.349-1.059.515-1.84.515-.468 0-.799-.03-1.024-.06v-3.917A7.947 7.947 0 0 1 11.66 14c.757 0 1.249.136 1.633.426.415.308.675.799.675 1.504 0 .763-.279 1.29-.663 1.615zM17 14.77h-1.532v.911H16.9v.734h-1.432v1.604h-.906V14.03H17v.74zM14 9h-1V4l5 5h-4z"></path></svg>
      </div>
      
      <div>
        <%= button_to  @billet, form: { data: { turbo_confirm: t('.delete') } }, method: :delete do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="fill-black hover:fill-red-400 " width="36" height="36" viewBox="0 0 24 24"><path d="M5 20a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8h2V6h-4V4a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2v2H3v2h2zM9 4h6v2H9zM8 8h9v12H7V8z"></path><path d="M9 10h2v8H9zm4 0h2v8h-2z"></path></svg>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div>
  <h1 class="font-bold text-4xl bg-red-500">Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
</div>